// <auto-generated />
using GsNetApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace GsNet.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251112215555_InitialStructureFluente")]
    partial class InitialStructureFluente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("SEU_SCHEMA_AQUI")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GsNetApi.Models.LocalizacaoTrabalho", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("GrausCelcius")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("GRAUS_CELCIUS");

                    b.Property<float>("NivelUmidade")
                        .HasColumnType("BINARY_FLOAT")
                        .HasColumnName("NIVEL_UMIDADE");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("TIPO");

                    b.HasKey("Id");

                    b.ToTable("TB_GS_LOCALIZACAO", "SEU_SCHEMA_AQUI");
                });

            modelBuilder.Entity("GsNetApi.Models.Login", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SENHA");

                    b.HasKey("Id");

                    b.ToTable("TB_GS_LOGIN", "SEU_SCHEMA_AQUI");
                });

            modelBuilder.Entity("GsNetApi.Models.Mensagem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("NivelEstresse")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NIVEL_ESTRESSE");

                    b.Property<string>("TextoMensagem")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("MENSAGEM");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_USUARIO");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TB_GS_MENSAGEM", "SEU_SCHEMA_AQUI");
                });

            modelBuilder.Entity("GsNetApi.Models.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("CPF");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("EMAIL");

                    b.Property<long>("LocalizacaoTrabalhoId")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_LOCAL_TRABALHO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("NOME");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("SENHA");

                    b.HasKey("Id");

                    b.HasIndex("LocalizacaoTrabalhoId");

                    b.ToTable("TB_GS_USUARIO", "SEU_SCHEMA_AQUI");
                });

            modelBuilder.Entity("GsNetApi.Models.Mensagem", b =>
                {
                    b.HasOne("GsNetApi.Models.Usuario", "Usuario")
                        .WithMany("Mensagens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_MENSAGEM_USUARIO");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("GsNetApi.Models.Usuario", b =>
                {
                    b.HasOne("GsNetApi.Models.LocalizacaoTrabalho", "LocTrabalho")
                        .WithMany("Usuarios")
                        .HasForeignKey("LocalizacaoTrabalhoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_USUARIO_LOCAL");

                    b.Navigation("LocTrabalho");
                });

            modelBuilder.Entity("GsNetApi.Models.LocalizacaoTrabalho", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("GsNetApi.Models.Usuario", b =>
                {
                    b.Navigation("Mensagens");
                });
#pragma warning restore 612, 618
        }
    }
}
